name: Run tests
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8.2"]
        os: [ubuntu-20.04, ubuntu-22.04, windows-latest]
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Print python-version
        run: python --version
  tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8.2"]
        os: [ubuntu-20.04, ubuntu-22.04, windows-latest]
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pytest
        run: pip install pytest
      - name: Run tests
        run: pytest -vv
  run_code:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8.2"]
        os: [ubuntu-20.04, ubuntu-22.04, windows-latest]
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dotenv
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv flask pandas
      - name: Create .env
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_LOGIN: ${{ secrets.LOGIN }}
          envkey_PASSWORD: ${{ secrets.PASSWORD }}
          file_name: .env
          directory: ${{pwd}}
      - name: Run code and print file
        run: |
          cat .env
          pip list
          ls
          python main.py
        

