name: Run tests
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.1'
      - name: Print python-version
        run: python --version
  tests:
    runs-on: windows-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.1'
      - name: Install pytest
        run: pip install pytest
      - name: Run tests
        run: pytest -vv
  run_code:
    runs-on: windows-latest
    steps:
      - name: Run code and print file
        run: |
          pwd
          ls
          python main.py
        

