name: Run tests
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.6'
      - name: Print python-version
        run: python --version
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.6'
      - name: Install pytest
        run: pip install pytest
      - name: Run tests
        run: pytest -vv
  run_code:
    runs-on: ubuntu-20.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.6'
      - name: Install dotenv
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv flask pandas
      - name: Run code and print file
        run: |
          pip list
          dir
        

